
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Book Listing App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <div className="h-full w-full bg-gray-300">
          <div className="h-1/6">
            <div className="h-1/2">
              <Navbar/>
            </div>
            <div className="h-1/2 flex text-center justify-center">
            <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-blue-600 sm:mb-0 xs:mb-0">Welcome to the book listing webpage!</h1>
            </div>
          </div>
          <div className="h-5/6 px-10 sm: px-4">      
              {children}      
          </div> 
        </div>
      </body>
    </html>
  );
}
